### ISSUE TITLE
Accessing ScreenShot Name on Save

### ISSUE THREAD

**Issue by MonzT** [atata-framework/atata#230]
Hi There. 

Using the Sample App, I've added 

```
AddScreenshotFileSaving().
     WithFileName(screenshotInfo => $"{screenshotInfo.Number:D2} - {screenshotInfo.PageObjectFullName}{screenshotInfo.Title?.Prepend(" - ")}").
```
to the AtataContext.Configure in the Setup Fixture. 

When the screenshot is taken, I'd like to write the FileName to the console. 
How can I access the FileName, that has been built up in the Setup, in my Test?

**Comment by YevgeniyShunevych** [comment]
Hi,

The full screenshot file path is automatically added to log with INFO log level in the following format:

```
Screenshot saved to file "...\Logs\2019-02-11 18_21_04\Plans\01 - Plans page - Failed.png"
```

Part of log file:

```
2019-02-11 18:21:13.3355 INFO Starting: Verify "1st" plan item's "Title" <h3> heading content should equal "Basic1"
2019-02-11 18:21:18.7554 ERROR Atata.AssertionException : Invalid "1st" plan item's "Title" <h3> heading content.
Expected: should equal "Basic1"
Actual: "Basic"

   at Atata.IDataVerificationProviderExtensions.Satisfy[TData,TOwner](IDataVerificationProvider`2 should, Predicate`1 predicate, String message, TData[] args)
   at Atata.IDataVerificationProviderExtensions.Equal[TData,TOwner](IDataVerificationProvider`2 should, TData expected)
   at AtataSampleApp.UITests.PlanTests.Plans() in C:\Development\atata-sample-app-tests\src\AtataSampleApp.UITests\PlanTests.cs:line 18
2019-02-11 18:21:18.7652 INFO Take screenshot #01 - Failed
2019-02-11 18:21:19.5028 INFO Screenshot saved to file "C:\Development\atata-sample-app-tests\src\AtataSampleApp.UITests\bin\Debug\Logs\2019-02-11 18_21_04\Plans\01 - Plans page - Failed.png"
2019-02-11 18:21:19.5058 INFO Starting: Clean up test context
```

Is it OK for you or you need to write such log line in a custom way?

**Comment by MonzT** [comment]
Hey, 
Thanks for the prompt response! 

I'm looking to do some custom stuff to add to my logs (using extent reporting). So was hoping there was a way to access just the file name on it's own if possible.

A couple of the things I tried, meant having to assign the filename in every test. If I could just grab the one that's already being created by Atata, it would simplify things.

Was just checking if there was already something in place, or if this would need to be a feature request.

**Comment by YevgeniyShunevych** [comment]
In addition to `FileScreenshotConsumer` being used, you can create custom `IScreenshotConsumer` to just track the file name:

```cs
public class ScreenshotTracker : IScreenshotConsumer
{
    public ScreenshotTracker(string fileNameFormat)
    {
        FileNameFormat = fileNameFormat;
    }

    public string FileNameFormat { get; }

    public void Take(ScreenshotInfo screenshotInfo)
    {
        string fileName = FileScreenshotConsumer.FormatPath(FileNameFormat, screenshotInfo).SanitizeForPath()
            + ScreenshotImageFormat.Png.GetExtension(); // Extension can be removed or made configurable.

        // Do custom tracking below:
        AtataContext.Current.Log.Info($"Screenshot file name: {fileName}");
    }
}
```

The screenshot file name can also be configurable via custom string format.

```cs
"{screenshot-number:D2} - {screenshot-pageobjectfullname}{screenshot-title: - *}"
```

which is equal to lambda analogue:

```cs
screenshotInfo => $"{screenshotInfo.Number:D2} - {screenshotInfo.PageObjectFullName}{screenshotInfo.Title?.Prepend(" - ")}"
```

Thus you can define file name format in some valiable (e.g. const in `UITestFixture` or in config):

```cs
string screenshotFileNameFormat = "{screenshot-number:D2} - {screenshot-pageobjectfullname}{screenshot-title: - *}";
```

Then add custom screenshot consumer to `AtataContext` and reuse variable in both consumers:

```cs
AtataContext.Configure().
    // ...
    AddScreenshotFileSaving().
        WithFileName(screenshotFileNameFormat).
    AddScreenshotConsumer(new ScreenshotTracker(screenshotFileNameFormat)).
    // ...
```

**Comment by MonzT** [comment]
This is awesome! Thank you. Will give it a bash tomorrow!
