### ISSUE TITLE
can't find angular md-select control

### ISSUE THREAD

**Issue by grimmersnee** [atata-framework/atata#343]
FIrst off, love the framework.  I'm having an issue trying to find and set values with rendered angular 1.5x material components.

example:

```
<md-select ng-change="regionChanged()" ng-disabled="!permissions.canEditForm || !permissions.canUpdatePaymentFields" name="region" ng-model="staging.region" required="" class="ng-valid ng-valid-required ng-touched ng-dirty ng-valid-parse" tabindex="0" role="listbox" aria-expanded="false" aria-multiselectable="false" id="select_6" aria-owns="select_container_7" aria-disabled="false" aria-required="false" aria-invalid="false" aria-label="Region: 
                                        Wellington
                                    " style=""><md-select-value class="_md-select-value" id="select_value_label_0"><span><div class="_md-text ng-binding">
                                        Wellington
                                    </div></span><span class="_md-select-icon" aria-hidden="true"></span></md-select-value></md-select>
```

**Comment by YevgeniyShunevych** [comment]
You need to create custom control class for that. You can take a look at [KendoDropDownList](https://github.com/atata-framework/atata-kendoui/blob/master/src/Atata.KendoUI/KendoDropDownList%602.cs) control as an example.

**Comment by grimmersnee** [comment]
Thanks for the reply.  I am finding that example a bit challenging to replicate for an md-select version. Is there a way to drop down to use webdriver and do something like the following? : https://stackoverflow.com/questions/39647437/cant-select-an-md-select-dropdown-option-using-selenium

**Comment by YevgeniyShunevych** [comment]
Here is the Gist of [MDSelect control](https://gist.github.com/YevgeniyShunevych/2732c2d989b4bf880d393eb9cd73e64f) for Angular JS Material Select. You can copy it to your solution and add modify if necessary.

Add it this way to the page object:

```cs
public MDSelect<string, _> SomeSelect { get; private set; }
```

**Comment by grimmersnee** [comment]
Thanks so much! I really appreciate your help.

**Comment by YevgeniyShunevych** [comment]
Welcome. Let me know if it will not work for you.

**Comment by grimmersnee** [comment]
sorry to be a proper pain in the ass', but having a few issues still.

Taking what you provided (which looked great), i got:

```
An exception of type 'OpenQA.Selenium.NoSuchElementException' occurred in Atata.WebDriverExtras.dll but was not handled in user code

Additional information: Unable to locate visible element:

- By.XPath: .//div[contains(concat(' ', normalize-space(@class), ' '), ' md-select-menu-container ')]
```

The source was:

```
<div class="_md-select-menu-container _md-active _md-clickable" aria-hidden="false" id="select_container_7" style="display: block; left: 353px; top: 414px; min-width: 494px; font-size: 14px;"><md-select-menu class="_md _md-overflow" style="transform-origin: 231px 24px 0px;"><md-content class="_md md-no-flicker" style="">
                                    <!-- ngRepeat: a in regions --><md-option ng-repeat="a in regions" ng-value="a" tabindex="0" class="ng-scope md-ink-ripple" role="option" aria-selected="true" id="select_option_17" value="[object Object]" selected="selected"><div class="_md-text ng-binding">
                                        Auckland
                                    </div><div class="md-ripple-container" style=""></div></md-option><!-- end ngRepeat: a in regions --><md-option ng-repeat="a in regions" ng-value="a" tabindex="0" class="ng-scope md-ink-ripple" role="option" aria-selected="false" id="select_option_18" value="[object Object]"><div class="_md-text ng-binding">
                                        Bay Of Plenty
                                    </div></md-option><!-- end ngRepeat: a in regions --><md-option ng-repeat="a in regions" ng-value="a" tabindex="0" class="ng-scope md-ink-ripple" role="option" aria-selected="false" id="select_option_19" value="[object Object]"><div class="_md-text ng-binding">
                                        Canterbury
                                    </div></md-option><!-- end ngRepeat: a in regions --><md-option ng-repeat="a in regions" ng-value="a" tabindex="0" class="ng-scope md-ink-ripple" role="option" aria-selected="false" id="select_option_20" value="[object Object]"><div class="_md-text ng-binding">
                                        Gisborne
                                    </div></md-option><!-- end ngRepeat: a in regions --><md-option ng-repeat="a in regions" ng-value="a" tabindex="0" class="ng-scope md-ink-ripple" role="option" aria-selected="false" id="select_option_21" value="[object Object]"><div class="_md-text ng-binding">
                                        Hawke's Bay
                                    </div></md-option><!-- end ngRepeat: a in regions --><md-option ng-repeat="a in regions" ng-value="a" tabindex="0" class="ng-scope md-ink-ripple" role="option" aria-selected="false" id="select_option_22" value="[object Object]"><div class="_md-text ng-binding">
                                        Manawatu / Wanganui
                                    </div></md-option><!-- end ngRepeat: a in regions --><md-option ng-repeat="a in regions" ng-value="a" tabindex="0" class="ng-scope md-ink-ripple" role="option" aria-selected="false" id="select_option_23" value="[object Object]"><div class="_md-text ng-binding">
                                        Wellington
                                    </div></md-option><!-- end ngRepeat: a in regions -->
</md-content></md-select-menu></div>
```

So I changed the control class container slightly to `_md-select-menu-container`, but then I got the error:

```
public class MDSelect<T, TOwner> : EditableField<T, TOwner> where TOwner : PageObject<TOwner>
    {
        [ControlDefinition("div", ContainingClass = "_md-select-menu-container", ComponentTypeName = "drop-down menu")]
        [FindFirst(ScopeSource = ScopeSource.Page)]
```

```


OpenQA.Selenium.ElementClickInterceptedException : element click intercepted: Element is not clickable at point (449, 1066)
  (Session info: chrome=80.0.3987.100)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at Atata.Control`1.Click()
   at Proppy.Tests.Selenium.Components.Custom.Atata.AngularJs.Material.MDSelect`2.SetValue(T value
```

i think the problem is because the actual content is in a child div with the `md-option` (but I could be wrong) -> 

```
<div class="_md-text ng-binding">
                                        Wellington
                                    </div>
```

**Comment by YevgeniyShunevych** [comment]
I see, strange a bit. Anyway you can try the following:

Change class of `MDOption.Text` property to `"_md-text"`:

```cs
[FindByClass("_md-text")]
public Text<TOwner> Text { get; private set; }
```

Then in `MDSelect.SetValue` method instead of `option.Click();` try `option.Text.Click();`.

If it doesn't work, try temporarily to add some "sleep" wait before the option click. Maybe something else is covering the drop-down options during it is opening.

**Comment by grimmersnee** [comment]
Ok I'm making progress.  I had added the class above in MDOption and added some debugging:

```
            foreach (var o in Options.Items)
            {
                var t = o.Value;

                Console.WriteLine(t);
            }
````
I was able to iterate the options, so they are in the values.

I'm also able to use linq to get it via:

````
var option = Options.Items.Select(o => o.Value.Equals(valueAsString)).SingleOrDefault();
````

So, the problem must be using xpath, which i am not the best at. It would be cool, if I could stick with the linq option, but I'm getting errors ..

````
var option = Options.Items.GetByXPathCondition(valueAsString, $"normalize-space(.) = '{valueAsString}'");
````

![image](https://user-images.githubusercontent.com/31529742/74569789-1f9ef080-4fe0-11ea-8e4a-dbac8f9fc45b.png)

**Comment by grimmersnee** [comment]
Ok I'm making progress.  I have added the class above in MDOption

I am able to find the right control using linq

````
protected override void SetValue(T value)
        {
            Click();

            var valueAsString = ConvertValueToStringUsingSetFormat(value);

            var option = Options.Items.SingleOrDefault(o => o.Value.Equals(valueAsString));

            option?.Click();
        }

````

But, I am getting error on: `option?.Click();`, I also tried `option?.Text.Click()` and also adding a sleep for 3 seconds before the click.

````
An exception of type 'OpenQA.Selenium.ElementClickInterceptedException' occurred in WebDriver.dll but was not handled in user code

Additional information: element click intercepted: Element is not clickable at point (449, 1066

````
I tried making the Text in the MDOption clickable, but still no go

````
[FindByClass("_md-text")]
public Clickable<TOwner> Text { get; private set; }
````

Looking at html below, I think I need the make the md-option clickable some how maybe, then navigate up to the parent?..

```
<md-option ng-repeat="a in regions" ng-value="a" tabindex="0" class="ng-scope md-ink-ripple" role="option" aria-selected="false" id="select_option_17" value="[object Object]">

    <div class="_md-text ng-binding">Auckland</div>

</md-option>
```

**Comment by grimmersnee** [comment]
I figured out the problem.  For some reason not having the browser maximized was causing issues finding the options in the animation.  I didn't think this would be a problem, since selenium is concerned with the Dom?

The following, sorted the issue.

```
UseChrome().
      WithArguments("start-maximized").
```

Thanks a heap for all your help!

**Comment by YevgeniyShunevych** [comment]
Strange. I haven't faced similiar issues. But OK, glad that you solved it.
