### ISSUE TITLE
Support for webDriver 3.5.2.0

### ISSUE THREAD

**Issue by DimaDubyk** [atata-framework/atata#77]
Exception is thrown for EditableField when I try to call Set method: Could not load type 'OpenQA.Selenium.Support.UI.IWait`1' from assembly 'WebDriver.Support, Version=3.5.2.0, Culture=neutral, PublicKeyToken=null'.

StackTrace:
   at Atata.ExtendedSearchContext`1.Until[TResult](Func`2 condition, Nullable`1 timeout, Nullable`1 retryInterval)
   at Atata.ExtendedSearchContext`1.FindAll(By by, SearchOptions options)
   at Atata.ExtendedSearchContext`1.Find(By by)
   at Atata.PlainScopeLocator.GetElement(SearchOptions searchOptions, String xPathCondition)
   at Atata.UIComponent`1.OnGetScopeElement(SearchOptions searchOptions)
   at Atata.UIComponent.GetScopeElement(SearchOptions searchOptions)
   at Atata.StrategyScopeLocator.GetScopeLocateResults(SearchOptions searchOptions)
   at Atata.StrategyScopeLocator.GetElement(SearchOptions searchOptions, String xPathCondition)
   at Atata.UIComponent`1.OnGetScopeElement(SearchOptions searchOptions)
   at Atata.UIComponent.GetScopeElement(SearchOptions searchOptions)
   at Atata.Input`2.SetValue(T value)
   at Atata.EditableField`2.Set(T value)

Browser: Chrome 60.0.3112.113 
OS: Windows 10
Atata: 0.13.0.0

**Comment by YevgeniyShunevych** [comment]
Hi,

I found out that there was a breaking change in v3.5.2 of WebDriver. Selenium moved `IWait<T>`, `DefaultWait<T>`, `WebDriverWait`, `IClock` and `SystemClock` from `WebDriver.Support` package to `WebDriver` package. I have no idea why have they done such a breaking change in minor release. So currently Atata does not work/support WebDriver v3.5.2 because of that.

Could you switch `WebDriver` and `WebDriver.Support` packages to v3.5.1 for now? Atata should work well with v3.5.1. I will have to do new releases of `Atata` and `Atata.WebDriverExtras` packages with support of WevDriver 3.5.2. But I need some time to do that.

**Comment by DimaDubyk** [comment]
HI, thanks for quick response. I will use v3.5.1 until fix is ready.

**Comment by YevgeniyShunevych** [comment]
[Atata 0.14.0 Released](https://atata-framework.github.io/blog/2017/09/22/atata-0.14.0-released/) with support of `WebDriver` v3.5.2.
