### ISSUE TITLE
"DevTools version is not in the supported range." under Ubuntu exception when taking snapshot

### ISSUE THREAD

**Issue by Piedone** [atata-framework/atata#839]
Using `AtataContext.TakePageSnapshot()` results in the following exception under the Ubuntu 22.04 runners of GitHub Actions. While this is swallowed and Atata does take a plain HTML snapshot instead of an MHTML one, I suppose this shouldn't happen all the time, what it does for me. E.g. in [this GitHub Actions workflow run](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/8910139820) and [this one](https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/8910493599).

This is with 3.1.0.

Windows runners don't have this issue.

```
2024-05-01T14:00:59.7669121Z  2024-05-01 13:51:48.718  WARN - Failed to take CDP snapshot. PageSource snapshot will be taken. OpenQA.Selenium.WebDriverException: Unexpected error creating WebSocket DevTools session.
2024-05-01T14:00:59.7669593Z   ---> OpenQA.Selenium.WebDriverException: DevTools version is not in the supported range. Desired version=114, range=5. Supported versions: 124, 123, 122, 85
2024-05-01T14:00:59.7669906Z     at OpenQA.Selenium.DevTools.DevToolsDomains.MatchDomainsVersion(Int32 desiredVersion, Int32 versionRange)
2024-05-01T14:00:59.7670283Z     at OpenQA.Selenium.DevTools.DevToolsDomains.InitializeDomains(Int32 protocolVersion, DevToolsSession session, Int32 versionRange)
2024-05-01T14:00:59.7670603Z     at OpenQA.Selenium.DevTools.DevToolsDomains.InitializeDomains(Int32 protocolVersion, DevToolsSession session)
2024-05-01T14:00:59.7670776Z     at OpenQA.Selenium.DevTools.DevToolsSession.StartSession()
2024-05-01T14:00:59.7671063Z     at OpenQA.Selenium.Chromium.ChromiumDriver.<>c__DisplayClass34_0.<<GetDevToolsSession>b__0>d.MoveNext()
2024-05-01T14:00:59.7671212Z  --- End of stack trace from previous location ---
2024-05-01T14:00:59.7671469Z     at OpenQA.Selenium.Chromium.ChromiumDriver.GetDevToolsSession(DevToolsOptions options)
2024-05-01T14:00:59.7671608Z     --- End of inner exception stack trace ---
2024-05-01T14:00:59.7671862Z     at OpenQA.Selenium.Chromium.ChromiumDriver.GetDevToolsSession(DevToolsOptions options)
2024-05-01T14:00:59.7672187Z     at OpenQA.Selenium.Chromium.ChromiumDriver.GetDevToolsSession()
2024-05-01T14:00:59.7673152Z     at Atata.CdpPageSnapshotStrategy.TakeSnapshot(AtataContext context)
2024-05-01T14:00:59.7674050Z     at Atata.CdpOrPageSourcePageSnapshotStrategy.TakeSnapshot(AtataContext context)
```

**Comment by Piedone** [comment]
I see, so the runner has an outdated Chrome, interesting, thank you.
